# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3c6987fd9d1d761733890a492d946a203f0d26a569a270dd57db12d9e75d1527d49e8877a18cfb22e1a89a824812d01a66a851b68eb3b5e1d6c7a8ffc6828122

test:
  secret_key_base: 2d14aa882be0a7e4a661c4e568c43abf07ded9bd3473ff74407a597fac8fd953dabc650c83fcffcbfe3805a158afb0cf7b18c3fa97a1e4c9df3c1d16eb44f6b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
